INSERT INTO Book_Language(Language_ID,language_name) VALUES (1,'English');
INSERT INTO Book_Language(Language_ID,language_name) VALUES (2,'Greek');
INSERT INTO Book_Language(Language_ID,language_name) VALUES (3,'Spanish');
INSERT INTO Book_Language(Language_ID,language_name) VALUES (4,'Italian');
INSERT INTO Book_Language(Language_ID,language_name) VALUES (5,'French');



INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (1,'Taifu Club (Taifû kurabu)','Hane LLC','0190851643',154,'horror','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (2,'Reefer Madness: The Movie Musical','Rowe LLC','0002005018',168,'history','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0002005018.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (3,'Manslaughter (Drabet)','Rowe-Bayer','0060973129',112,'satire','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0060973129.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (4,'Syrinx','Feeney, Ziemann and Howell','0374157065',112,'fantasy','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/0374157065.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (5,'Night at the Museum: Battle of the Smithsonian','Nader, McKenzie and Larson','0393045218',89,'comedy','A woman must choose between two very different paths in life.','http://images.amazon.com/images/P/0393045218.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (6,'For the Bible Tells Me So','Kerluke Inc','0399135782',193,'drama','A young girl discovers a magical world hidden within her own wardrobe.','https://m.media-amazon.com/images/I/51T4zZCl9LL._SX316_BO1,204,203,200_.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (7,'Dead Pit, The','Abshire, Zemlak and Gleason','0425176428',112,'travel','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0425176428.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (8,'Wise Blood','Lueilwitz and Sons','0002240149',137,'comedy','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/I/71Ms31D84kL.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (9,'Cover Girl','Skiles, Pagac and Bins','0679425608',126,'horror','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0679425608.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (10,'Hidden Blade, The (Kakushi ken oni no tsume)','Nienow-Schmitt','0684815109',168,'adventure','A man travels back in time to prevent a historical event from occurring.','http://images.amazon.com/images/P/074322678X.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (11,'Silent Night, Deadly Night Part 2','White, Auer and Schultz','0771074603',75,'travel','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0771074670.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (12,'Dragon Tiger Gate (Lung fu moon)','Prohaska-O''Hara','1559724218',179,'mystery','A young girl discovers a magical world hidden within her own wardrobe.','http://images.amazon.com/images/P/080652121X.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (13,'Phantom of the Opera','Bayer Group','1936365906',193,'travel','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/I/31q1qG1oiJL.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (14,'Last Seven, The','Hansen, Kuhn and Mayert','‎1558746220',103,'science fiction','A group of friends embark on a dangerous journey to destroy a powerful ring.','https://m.media-amazon.com/images/P/B076V125RV.01._SCLZZZZZZZ_SX500_.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (15,'Where the Red Fern Grows','Simonis Group','1558746218',154,'science fiction','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/1558746218.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (16,'Carmen','Harber Inc','1567405819',179,'travel','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/1567407781.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (17,'Crumb','Pollich Group','1575663937',103,'science fiction','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/1575663937.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (18,'Thomas and the Magic Railroad','Prosacco LLC','1881320189',112,'self-help','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/I/41uVmNqyeXL._SX315_BO1,204,203,200_.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (19,'Archangel','Wintheiser LLC','0440234743',168,'poetry','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0440234743.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (20,'Dark Horse, The','Bartell-Wiza','0452264464',168,'fiction','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/P/1400033411.01._SCLZZZZZZZ_SX500_.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (21,'Girl with Hyacinths','Roberts-Harber','0609804618',137,'drama','A woman must choose between two very different paths in life.','http://images.amazon.com/images/P/0609804618.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (22,'Death on the Staircase (Soupçons)','Dooley-Klein','1841721522',103,'fiction','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/1841721522.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (23,'My Favorite Season','Kunde-Crooks','1879384493',179,'fantasy','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/1879384493.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (24,'Venus in Fur (La Vénus à la fourrure)','Wuckert Inc','0061076031',112,'autobiography','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0061076031.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (25,'Brides of Dracula','Hansen-Tromp','0439095026',168,'science fiction','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0439095026.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (26,'Turning Tide (En solitaire)','Yundt, Kuhlman and Ondricka','0689821166',103,'non-fiction','A young couple falls in love despite their families'' long-standing feud.','https://m.media-amazon.com/images/P/B00KU4O28W.01._SCLZZZZZZZ_SX500_.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (27,'Drunken Master (Jui kuen)','Cartwright Inc','0971880107',154,'history','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0971880107.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (28,'Secret Glory, The','Stokes, Murazik and Effertz','0345402871',89,'fantasy','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0345402871.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (29,'Renoir','Flatley LLC','0345417623',126,'biography','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0345417623.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (30,'Forgiveness of Blood, The (Falja e gjakut)','Murphy, Miller and Ratke','0684823802',137,'romance','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0684823802.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (31,'Night, The (Notte, La)','Huels, Larson and White','0375759778',193,'science fiction','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/I/516IajBgM4L.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (32,'White Rose, The (Weiße Rose, Die)','King-Champlin','0425163091',137,'self-help','A young girl discovers a magical world hidden within her own wardrobe.','http://images.amazon.com/images/P/0425163091.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (33,'Tetsuo II: Body Hammer','Kozey, Nicolas and Davis','3446198512',168,'thriller','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/3404921038.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (34,'Jonah Who Will Be 25 in the Year 2000 (Jonas qui aura 25 ans en l''an 2000)','Predovic, Bechtelar and Bergstrom','3442353866',103,'self-help','A group of friends embark on a dangerous journey to destroy a powerful ring.','https://m.media-amazon.com/images/I/41MEpZKMZcL._SX331_BO1,204,203,200_.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (35,'Finders Keepers','Harber, Emard and Hamill','3442410665',137,'science fiction','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/3442410665.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (36,'Ruby Cairo','Abshire LLC','3570001415',168,'autobiography','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/3442446937.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (37,'Great Ecstasy of Robert Carmichael, The','Hintz-Torp','0375706062',126,'non-fiction','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/0375406328.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (38,'Clique, The','Leuschke, Jacobs and Stracke','‎ 3499217546',75,'history','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0446310786.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (39,'Trailer Park Boys: The Movie','Robel LLC','0375502912',89,'adventure','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0449005615.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (40,'J. Gang Meets Dynamite Harry, The (Jönssonligan & DynamitHarry)','Kreiger, Kub and Streich','0060168013',179,'autobiography','A woman must choose between two very different paths in life.','https://m.media-amazon.com/images/I/41m4kEbAcRL.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (41,'Lumberjacking (Nuoruuteni savotat)','Nikolaus Group','0380806743',126,'horror','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/I/51w5uB4dWFL.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (42,'M for Mother (Mim mesle madar)','Lesch Group','1676097708',137,'cookbook','A woman navigates life and love in New York City.','https://m.media-amazon.com/images/I/51ONPDRzewL.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (43,'Cyborg Girl (Boku no kanojo wa saibôgu)','Gerhold, Romaguera and Kiehn','671765373',137,'autobiography','A group of survivors must band together to survive a zombie apocalypse.','http://images.amazon.com/images/P/067176537X.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (44,'Tingler, The','Gusikowski-Graham','0061099686',137,'romance','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/I/51UwA6llplL.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (45,'Dirty Sanchez: The Movie','Williamson, Pagac and Schiller','0553582909',89,'fantasy','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0553582909.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (46,'Alvin and the Chipmunks','Hirthe-Zulauf','0671888589',89,'history','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0671888587.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (47,'Very Ordinary Couple (Yeonaeui Wondo)','Block, Carter and Ebert','0553582747',112,'history','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0553582747.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (48,'If You Are the One','Watsica-Grant','0425182908',154,'self-help','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/0425182908.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (49,'St. Vincent','Fadel Inc','425186302',154,'thriller','A young girl discovers a magical world hidden within her own wardrobe.','http://images.amazon.com/images/P/042518630X.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (50,'Night of the Living Dead','Mills, McCullough and Ruecker','0440223571',168,'romance','A young girl discovers a magical world hidden within her own wardrobe.','http://images.amazon.com/images/P/0440223571.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (51,'Elena and Her Men (Paris Does Strange Things) (Elena et les hommes)','Davis, Bahringer and Stark','0812523873',193,'poetry','A man travels back in time to prevent a historical event from occurring.','http://images.amazon.com/images/P/0812523873.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (52,'Sleepwalkers','Schiller Inc','0842342702',179,'horror','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0842342702.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (53,'American Movie','Dickinson, McDermott and Hayes','0440225701',89,'mystery','A man travels back in time to prevent a historical event from occurring.','http://images.amazon.com/images/P/0440225701.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (54,'Angels Fall','Botsford Group','0060914068',112,'thriller','A boy befriends a giant creature and helps him return home.','https://m.media-amazon.com/images/P/B005AJQKBO.01._SCLZZZZZZZ_SX500_.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (55,'Winnie the Pooh','Cummings Inc','0156047624',75,'biography','A scientist creates a monster that ultimately turns on him.','https://m.media-amazon.com/images/I/21SybjH7HyL._BO1,204,203,200_.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (56,'Victory Through Air Power','Leannon-Rodriguez','0245542957',137,'fiction','A boy befriends a giant creature and helps him return home.','https://i.ebayimg.com/images/g/ky4AAOSw-1ZckKwH/s-l500.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (57,'The Boys','Bernhard and Sons','0156031132',103,'science fiction','A young couple falls in love despite their families'' long-standing feud.','https://m.media-amazon.com/images/P/0151836000.01._SCLZZZZZZZ_SX500_.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (58,'Barrier (Bariera)','Huels LLC','0553280333',75,'adventure','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0553280333.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (59,'Man with the Iron Fists, The','Brekke, Fritsch and Jacobi','9600348200',112,'horror','A young girl discovers a magical world hidden within her own wardrobe.','https://m.media-amazon.com/images/I/31PnN+8+lJL._BO1,204,203,200_.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (60,'Beautiful Girls','Kessler-Abshire','0964778319',103,'comedy','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/0964778319.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (61,'Rules of Attraction, The','Zemlak Group','0671623249',75,'science fiction','A young girl discovers a magical world hidden within her own wardrobe.','https://external.webstorage.gr/mmimages/image/61/86/49/28/1049773-264x264-800x800-96x96-560x560.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (62,'City Heat','Padberg-Maggio','0679810307',126,'science fiction','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0679810307.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (63,'Treasure of the Four Crowns','Hartmann, Davis and Stoltenberg','0679865691',75,'self-help','A detective solves a series of murders in a small town.','https://www.politeianet.gr/components/com_virtuemart/shop_image/product/2aec40d2-5aab-4899-92d4-f8b610a469a0.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (64,'Ciao, Professore! (Io speriamo che me la cavo)','Bruen, Robel and Wilkinson','1741751683',154,'travel','A young girl discovers a magical world hidden within her own wardrobe.','https://m.media-amazon.com/images/P/0385340990.01._SCLZZZZZZZ_SX500_.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (65,'Last Movie, The','Schoen-Kautzer','0345260317',179,'satire','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/P/0345346297.01._SCLZZZZZZZ_SX500_.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (66,'Merlin''s Apprentice','Carroll, Dicki and Von','0394743741',89,'adventure','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/I/71BJAXVFnSL.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (67,'Dark Night of the Scarecrow','Hilpert-Rice','425117744',103,'autobiography','A young couple falls in love despite their families'' long-standing feud.','https://m.media-amazon.com/images/I/41VbiRPDmtL._SX322_BO1,204,203,200_.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (68,'Santa Sangre','Parker-Reilly','0553808044',126,'memoir','A scientist creates a monster that ultimately turns on him.','https://m.media-amazon.com/images/P/0553808044.01._SCLZZZZZZZ_SX500_.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (69,'Everly','Kub, Bauch and Lowe','1647225280',75,'adventure','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/P/1647225280.01._SCLZZZZZZZ_SX500_.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (70,'Trekkies','Wolff, Waelchi and Yundt','0062342409',168,'cookbook','A young couple falls in love despite their families'' long-standing feud.','https://m.media-amazon.com/images/P/0062342401.01._SCLZZZZZZZ_SX500_.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (71,'Jönssonligan spelar högt','Cormier-Swift','1853260053',75,'cookbook','A woman must choose between two very different paths in life.','http://images.amazon.com/images/P/1853260053.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (72,'Bakhita','Veum, Cremin and Wiza','1414035004',137,'biography','A group of survivors must band together to survive a zombie apocalypse.','http://images.amazon.com/images/P/1414035004.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (73,'Bachelor Weekend, The','Bradtke and Sons','0060938412',126,'cookbook','A woman must choose between two very different paths in life.','http://images.amazon.com/images/P/0060938412.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (74,'Siberia','Stamm Group','0140067477',75,'thriller','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/0140067477.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (75,'Winter Nomads','Goldner-Conn','0345465083',112,'autobiography','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0345465083.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (76,'Hatful of Rain, A','Roob, Kautzer and Skiles','‎ 0857087827',75,'memoir','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/P/0857087827.01._SCLZZZZZZZ_SX500_.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (77,'War Made Easy: How Presidents & Pundits Keep Spinning Us to Death','Lesch-Gibson','8374102581',168,'thriller','A scientist creates a monster that ultimately turns on him.','http://images.amazon.com/images/P/1558531025.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (78,'Mr. Smith Goes to Washington','Hilll-Price','0241469406',179,'history','A man travels back in time to prevent a historical event from occurring.','https://m.media-amazon.com/images/P/B0972BTWSF.01._SCLZZZZZZZ_SX500_.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (79,'Sunset Strip','Kling, Kilback and Daniel','0394895894',89,'memoir','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/P/074402868X.01._SCLZZZZZZZ_SX500_.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (80,'Stage Fright (Deliria)','Hills-O''Keefe','1569871213',103,'science fiction','A woman must choose between two very different paths in life.','http://images.amazon.com/images/P/1569871213.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (81,'Foon','Price, Flatley and Altenwerth','0375410538',168,'cookbook','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0375410538.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (82,'You Kill Me','Keebler Inc','1422196024',89,'comedy','A group of survivors must band together to survive a zombie apocalypse.','https://m.media-amazon.com/images/P/142219602X.01._SCLZZZZZZZ_SX500_.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (83,'Why Man Creates','Herman-Wuckert','871133753',75,'mystery','A man travels back in time to prevent a historical event from occurring.','http://images.amazon.com/images/P/087113375X.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (84,'Copper Mountain','Marvin and Sons','0340767936',168,'romance','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0340767936.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (85,'Hans (Kukkulan kuningas)','Grady Inc','0743403843',168,'thriller','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/0743403843.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (86,'Fools Rush In','Roberts Inc','0060930365',126,'self-help','A man travels back in time to prevent a historical event from occurring.','http://images.amazon.com/images/P/0060930365.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (87,'Leave','Brekke, Corwin and Goyette','0060177586',193,'comedy','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0060177586.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (88,'Kiss Me (Kyss Mig)','Jerde, McClure and Jerde','0071416331',89,'cookbook','A young girl discovers a magical world hidden within her own wardrobe.','http://images.amazon.com/images/P/0071416331.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (89,'Noroi: The Curse','O''Keefe LLC','0375509038',154,'fantasy','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0375509038.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (90,'Ratatouille','Witting LLC','1408845660',193,'drama','A detective solves a series of murders in a small town.','https://m.media-amazon.com/images/I/91B+zGZxJ6L.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (91,'Thompsons, The','Jenkins, Gislason and Reichert','0316769487',89,'history','A woman navigates life and love in New York City.','http://images.amazon.com/images/P/0316769487.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (92,'What''s Up, Scarlet?','Trantow, Vandervort and Flatley','8445071408',126,'science fiction','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/8445071408.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (93,'Gleaming the Cube','Pacocha, Haag and Padberg','8445071769',193,'horror','A young couple falls in love despite their families'' long-standing feud.','http://images.amazon.com/images/P/8445071769.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (94,'Kisses for My President','Hackett Inc','8445071777',179,'satire','A boy befriends a giant creature and helps him return home.','http://images.amazon.com/images/P/8445071777.01.LZZZZZZZ.jpg',4);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (95,'Eye of the Tiger','Zieme, Gorczany and Halvorson','0679429220',168,'cookbook','A group of survivors must band together to survive a zombie apocalypse.','http://images.amazon.com/images/P/0679429220.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (96,'Capone','Nicolas Group','0671867156',126,'science fiction','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0671867156.01.LZZZZZZZ.jpg',3);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (97,'Stag','Ortiz LLC','0312252617',154,'horror','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0312252617.01.LZZZZZZZ.jpg',5);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (98,'Fireflies in the Garden','Conn, O''Keefe and Willms','0312261594',103,'comedy','A group of friends embark on a dangerous journey to destroy a powerful ring.','http://images.amazon.com/images/P/0312261594.01.LZZZZZZZ.jpg',1);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (99,'Des fleurs pour Algernon','Wiegand-Rowe','0316748641',154,'adventure','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0316748641.01.LZZZZZZZ.jpg',2);
INSERT INTO book(Book_ID,title,publisher,ISBN,pg_numbers,keyword,summary,image_URL,Language_ID) VALUES (100,'Meet the Fockers','Hoppe, Klein and Bartell','0316973742',154,'cookbook','A detective solves a series of murders in a small town.','http://images.amazon.com/images/P/0316973742.01.LZZZZZZZ.jpg',4);




INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (1,'leok','123','nlapthorne0@technorati.com','Norene','Lapthorne',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (2,'thanok','123','lridett1@addtoany.com','Leonidas','Ridett',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (3,'iasonal','123','msorrie2@vistaprint.com','Murry','Sorrie',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (4,'edebischof3','K1mnnF','edebischof3@amazon.de','Ev','De Bischof',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (5,'woflaherty4','mJpyxmbAV3g','woflaherty4@google.ca','Winfred','O'' Flaherty',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (6,'boager5','PlGqX3B03c8','boager5@bbc.co.uk','Brockie','Oager',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (7,'sodoogan6','d4OPFtL1S0Gt','sodoogan6@acquirethisname.com','Silva','O''Doogan',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (8,'gfellowes7','Rqp1lvTle','gfellowes7@vistaprint.com','Galvin','Fellowes',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (9,'npietesch8','PPU91dm','npietesch8@weebly.com','Norbert','Pietesch',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (10,'jmcgaughey9','dUcvVempjG','jmcgaughey9@so-net.ne.jp','Jaymee','Mc Gaughey',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (11,'ccawthrya','SeTDFF9ctc3P','ccawthrya@reuters.com','Clerc','Cawthry',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (12,'jhogbourneb','4scrbmf','jhogbourneb@chronoengine.com','Jocelyne','Hogbourne',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (13,'wletsonc','2X6uwNNa','wletsonc@wiley.com','Wenonah','Letson',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (14,'cluckesd','b0n1lxdvSb','cluckesd@weibo.com','Chancey','Luckes',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (15,'vorricke','tUdTbEGSTyg','vorricke@ca.gov','Veronica','Orrick',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (16,'mpattinif','ZB1FlMY','mpattinif@cafepress.com','Maximilianus','Pattini',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (17,'kathridgeg','4eHSWzutkH','kathridgeg@amazon.com','Koral','Athridge',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (18,'bwadhamh','67cFzFyXz','bwadhamh@bravesites.com','Brendis','Wadham',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (19,'mfussiei','7ac8olMJl','mfussiei@constantcontact.com','Merlina','Fussie',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (20,'tjoreauj','lvaqumvQC','tjoreauj@ycombinator.com','Tom','Joreau',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (21,'dklimkovichk','vfNlQj','dklimkovichk@dedecms.com','Delphinia','Klimkovich',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (22,'sferschkel','mEYf8sF','sferschkel@alibaba.com','Sara-ann','Ferschke',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (23,'vbrockleym','6Hqaqg0','vbrockleym@newyorker.com','Valenka','Brockley',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (24,'rgheeraertn','W0d5OcsPHz','rgheeraertn@slideshare.net','Robenia','Gheeraert',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (25,'fhaileso','kaRIWiynUB1u','fhaileso@cnn.com','Franny','Hailes',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (26,'samblerp','uX7sSA2BE','samblerp@theatlantic.com','Syman','Ambler',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (27,'wbrandrickq','GcI9bzI','wbrandrickq@blog.com','Woodman','Brandrick',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (28,'gcurwenr','dOdo85','gcurwenr@whitehouse.gov','Gran','Curwen',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (29,'rtraylens','2TkLPmq','rtraylens@loc.gov','Rafaelia','Traylen',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (30,'cwolveyt','ytQ3tip7Lw','cwolveyt@usgs.gov','Court','Wolvey',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (31,'mstonebridgeu','cqgW4H','mstonebridgeu@jimdo.com','Mariejeanne','Stonebridge',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (32,'tlacrouxv','mhq0hki','tlacrouxv@51.la','Taddeo','Lacroux',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (33,'jgourliew','AYxobDD','jgourliew@google.com.au','Josiah','Gourlie',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (34,'cdrewesx','Gzlo8Qj6OY','cdrewesx@aboutads.info','Crystal','Drewes',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (35,'fharbary','BbMbqCKlT','fharbary@parallels.com','Frieda','Harbar',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (36,'vbartenz','e6uR21AL23','vbartenz@senate.gov','Vivienne','Barten',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (37,'adalesio10','8NMZbeXohNL','adalesio10@eventbrite.com','Anton','D''Alesio',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (38,'lkubczak11','ZmNzAYvrj','lkubczak11@e-recht24.de','Lindsay','Kubczak',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (39,'crosenbloom12','qCDOLR5Xio4','crosenbloom12@webmd.com','Cassius','Rosenbloom',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (40,'cbuxcey13','ouTBWvFMGqT','cbuxcey13@deliciousdays.com','Carolann','Buxcey',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (41,'lgiberd14','BggG25b','lgiberd14@photobucket.com','Lauretta','Giberd',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (42,'efraschini15','mfIYMEL2ij','efraschini15@bloglovin.com','Ernesto','Fraschini',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (43,'nkingham16','o3iEi70c4kjE','nkingham16@vistaprint.com','Nolly','Kingham',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (44,'ktire17','ObUl9igKtH','ktire17@mayoclinic.com','Korry','Tire',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (45,'dparades18','Z2SMAOYOs','dparades18@huffingtonpost.com','Debora','Parades',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (46,'npreshous19','FymTw9d','npreshous19@tripod.com','Nelle','Preshous',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (47,'lvella1a','hxYUKfQ','lvella1a@stanford.edu','Lyndsie','Vella',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (48,'hchedzoy1b','JiJ6xSHz','hchedzoy1b@typepad.com','Hendrika','Chedzoy',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (49,'ydruel1c','qd6kYcZEKml','ydruel1c@uol.com.br','Yalonda','D''Ruel',1);
INSERT INTO users(User_ID,username,user_password,Email,first_name,last_name,approved) VALUES (50,'jeyers1d','8bcrqXzWY9','jeyers1d@timesonline.co.uk','Jimmie','Eyers',1);



INSERT INTO administrator(Admin_ID,User_ID) VALUES (1,38);
INSERT INTO administrator(Admin_ID,User_ID) VALUES (2,50);
INSERT INTO administrator(Admin_ID,User_ID) VALUES (3,41);
INSERT INTO administrator(Admin_ID,User_ID) VALUES (4,30);
INSERT INTO administrator(Admin_ID,User_ID) VALUES (5,16);


INSERT INTO school_unit(School_ID, School_name, address, City, Telephone, email, principal_fullname, Admin_ID)
VALUES (1, 'Reynolds, Ward and Hauck', '59 Porter Lane', 'Conduaga', '2102427853', 'adespenser0@technorati.com', 'Aimil Despenser', 5);
INSERT INTO school_unit(School_ID, School_name, address, City, Telephone, email, principal_fullname, Admin_ID)
VALUES (2, 'Bradtke, Boyer and Grant', '181 Gulseth Avenue', 'Võhma', '2102427852', 'dchasmer1@cmu.edu', 'Daniel Chasmer', 4);
INSERT INTO school_unit(School_ID, School_name, address, City, Telephone, email, principal_fullname, Admin_ID)
VALUES (3, 'Strosin Inc', '04921 Sunbrook Drive', 'Panggunguni', '2152457853', 'aherety2@icio.us', 'Amber Herety', 3);
INSERT INTO school_unit(School_ID, School_name, address, City, Telephone, email, principal_fullname, Admin_ID)
VALUES (4, 'Welch, Lowe and O''Kon', '4120 Namekagon Drive', 'Magway', '2105477053', 'jagnolo3@xinhuanet.com', 'Jennifer Agnolo', 2);
INSERT INTO school_unit(School_ID, School_name, address, City, Telephone, email, principal_fullname, Admin_ID)
VALUES (5, 'Cummerata-Sanford', '4 American Center', 'Kristinehamn', '2105477053', 'bleggin4@jigsy.com', 'Bryn Leggin', 1);


INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (1,1,'1970-10-01',1,1);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (2,1,'1973-06-23',2,2);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (3,1,'1983-03-11',3,47);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (4,1,'1984-01-05',4,4);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (5,1,'1985-06-18',5,15);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (6,1,'1991-02-06',1,6);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (7,1,'1992-10-07',2,7);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (8,1,'1992-11-10',3,8);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (9,1,'1994-10-17',4,9);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (10,1,'1994-12-13',5,10);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (11,0,'2011-10-07',1,11);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (12,0,'2011-10-22',2,12);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (13,0,'2012-02-06',3,13);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (14,0,'2014-04-10',4,14);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (15,0,'2014-09-07',5,42);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (16,0,'2015-11-24',1,43);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (17,0,'2018-11-17',2,17);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (18,0,'2018-12-30',3,18);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (19,0,'2019-03-10',4,19);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (20,0,'2019-09-11',5,20);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (21,0,'2008-10-03',1,21);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (22,0,'2008-11-27',2,22);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (23,0,'2008-12-06',3,23);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (24,0,'2011-01-26',4,24);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (25,0,'2013-12-30',5,25);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (26,0,'2015-03-14',1,26);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (27,0,'2015-05-28',2,27);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (28,0,'2015-09-19',3,28);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (29,0,'2009-02-23',4,29);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (30,0,'2009-05-23',5,44);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (31,0,'2011-05-25',1,31);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (32,0,'2018-04-02',2,32);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (33,0,'2018-07-17',3,33);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (34,0,'2019-03-31',4,45);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (35,0,'2019-04-12',5,35);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (36,0,'2019-08-13',1,36);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (37,0,'2019-09-07',2,37);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (38,0,'2020-07-12',3,46);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (39,0,'2010-01-06',4,39);
INSERT INTO Students_Professors(studprof_id,Is_Professor,Date_of_birth,School_ID,User_ID) VALUES (40,0,'2010-09-05',5,40);


INSERT INTO School_Unit_Manager(Manager_ID,School_ID,Admin_ID,User_ID) VALUES (1,1,5,48);
INSERT INTO School_Unit_Manager(Manager_ID,School_ID,Admin_ID,User_ID) VALUES (2,2,4,49);
INSERT INTO School_Unit_Manager(Manager_ID,School_ID,Admin_ID,User_ID) VALUES (3,3,1,5);
INSERT INTO School_Unit_Manager(Manager_ID,School_ID,Admin_ID,User_ID) VALUES (4,4,1,3);
INSERT INTO School_Unit_Manager(Manager_ID,School_ID,Admin_ID,User_ID) VALUES (5,5,4,34);



INSERT INTO Author(Author_ID,author_fullname) VALUES (1,'Antonia Erat');
INSERT INTO Author(Author_ID,author_fullname) VALUES (2,'Bobinette Lazar');
INSERT INTO Author(Author_ID,author_fullname) VALUES (3,'Brander Pietersma');
INSERT INTO Author(Author_ID,author_fullname) VALUES (4,'Skip Bryns');
INSERT INTO Author(Author_ID,author_fullname) VALUES (5,'Cord Ech');
INSERT INTO Author(Author_ID,author_fullname) VALUES (6,'Esmeralda Antoons');
INSERT INTO Author(Author_ID,author_fullname) VALUES (7,'Morey Menco');
INSERT INTO Author(Author_ID,author_fullname) VALUES (8,'Bertrando Niessen');
INSERT INTO Author(Author_ID,author_fullname) VALUES (9,'Nicky Ballard');
INSERT INTO Author(Author_ID,author_fullname) VALUES (10,'Leeann Kellick');
INSERT INTO Author(Author_ID,author_fullname) VALUES (11,'Margalit Jehan');
INSERT INTO Author(Author_ID,author_fullname) VALUES (12,'Loretta Groves');
INSERT INTO Author(Author_ID,author_fullname) VALUES (13,'Weider Ipwell');
INSERT INTO Author(Author_ID,author_fullname) VALUES (14,'Hershel Drummer');
INSERT INTO Author(Author_ID,author_fullname) VALUES (15,'Clementius Macklam');
INSERT INTO Author(Author_ID,author_fullname) VALUES (16,'Gaspar Claige');
INSERT INTO Author(Author_ID,author_fullname) VALUES (17,'Jenda Labeuil');
INSERT INTO Author(Author_ID,author_fullname) VALUES (18,'Juan Auletta');
INSERT INTO Author(Author_ID,author_fullname) VALUES (19,'Devan Hance');
INSERT INTO Author(Author_ID,author_fullname) VALUES (20,'Dill Scotsbrook');
INSERT INTO Author(Author_ID,author_fullname) VALUES (21,'Jacquelin Bowen');
INSERT INTO Author(Author_ID,author_fullname) VALUES (22,'Nat Dungee');
INSERT INTO Author(Author_ID,author_fullname) VALUES (23,'Fayth Craske');
INSERT INTO Author(Author_ID,author_fullname) VALUES (24,'Ardella Beteriss');
INSERT INTO Author(Author_ID,author_fullname) VALUES (25,'Leonelle Folonin');
INSERT INTO Author(Author_ID,author_fullname) VALUES (26,'Nikolas Screaton');
INSERT INTO Author(Author_ID,author_fullname) VALUES (27,'Con Cuberley');
INSERT INTO Author(Author_ID,author_fullname) VALUES (28,'Rozanne Vidgen');
INSERT INTO Author(Author_ID,author_fullname) VALUES (29,'Abeu Jannings');
INSERT INTO Author(Author_ID,author_fullname) VALUES (30,'Addison Braine');
INSERT INTO Author(Author_ID,author_fullname) VALUES (31,'Leoline Bussey');
INSERT INTO Author(Author_ID,author_fullname) VALUES (32,'Brody Arndell');
INSERT INTO Author(Author_ID,author_fullname) VALUES (33,'Joice Langhorne');
INSERT INTO Author(Author_ID,author_fullname) VALUES (34,'Guillaume Buske');
INSERT INTO Author(Author_ID,author_fullname) VALUES (35,'Olvan Devoy');
INSERT INTO Author(Author_ID,author_fullname) VALUES (36,'Daria Plinck');
INSERT INTO Author(Author_ID,author_fullname) VALUES (37,'Rosene Harvard');
INSERT INTO Author(Author_ID,author_fullname) VALUES (38,'Neddie Devil');
INSERT INTO Author(Author_ID,author_fullname) VALUES (39,'Annnora Semper');
INSERT INTO Author(Author_ID,author_fullname) VALUES (40,'Kipp Fryd');
INSERT INTO Author(Author_ID,author_fullname) VALUES (41,'Ramonda Turmel');
INSERT INTO Author(Author_ID,author_fullname) VALUES (42,'Nanete Mallan');
INSERT INTO Author(Author_ID,author_fullname) VALUES (43,'Patrick Povlsen');
INSERT INTO Author(Author_ID,author_fullname) VALUES (44,'Leisha Arundel');
INSERT INTO Author(Author_ID,author_fullname) VALUES (45,'Brody Binden');
INSERT INTO Author(Author_ID,author_fullname) VALUES (46,'Karine Cuddehay');
INSERT INTO Author(Author_ID,author_fullname) VALUES (47,'Link Knotte');
INSERT INTO Author(Author_ID,author_fullname) VALUES (48,'Ingram Lanbertoni');
INSERT INTO Author(Author_ID,author_fullname) VALUES (49,'Carlo Geram');
INSERT INTO Author(Author_ID,author_fullname) VALUES (50,'Vachel Ellacott');
INSERT INTO Author(Author_ID,author_fullname) VALUES (51,'Coleen Dobney');
INSERT INTO Author(Author_ID,author_fullname) VALUES (52,'Edee Hearsum');
INSERT INTO Author(Author_ID,author_fullname) VALUES (53,'Kerk Rushbury');
INSERT INTO Author(Author_ID,author_fullname) VALUES (54,'Derrick Cutsforth');
INSERT INTO Author(Author_ID,author_fullname) VALUES (55,'Christian Beadles');
INSERT INTO Author(Author_ID,author_fullname) VALUES (56,'Jeramie Colton');
INSERT INTO Author(Author_ID,author_fullname) VALUES (57,'Rita Livard');
INSERT INTO Author(Author_ID,author_fullname) VALUES (58,'Brit Jakoub');
INSERT INTO Author(Author_ID,author_fullname) VALUES (59,'Barry Ridolfo');
INSERT INTO Author(Author_ID,author_fullname) VALUES (60,'Seymour Fairnington');
INSERT INTO Author(Author_ID,author_fullname) VALUES (61,'Rubi Mowlam');
INSERT INTO Author(Author_ID,author_fullname) VALUES (62,'Gerek Bullier');
INSERT INTO Author(Author_ID,author_fullname) VALUES (63,'Justinn Cissen');
INSERT INTO Author(Author_ID,author_fullname) VALUES (64,'Thoma Khan');
INSERT INTO Author(Author_ID,author_fullname) VALUES (65,'Karoly Kryszka');
INSERT INTO Author(Author_ID,author_fullname) VALUES (66,'Tallulah Gosker');
INSERT INTO Author(Author_ID,author_fullname) VALUES (67,'Dotti Botton');
INSERT INTO Author(Author_ID,author_fullname) VALUES (68,'Humfrey Desvignes');
INSERT INTO Author(Author_ID,author_fullname) VALUES (69,'Shay Wybern');
INSERT INTO Author(Author_ID,author_fullname) VALUES (70,'Monroe Hance');
INSERT INTO Author(Author_ID,author_fullname) VALUES (71,'Gilburt Dinneges');
INSERT INTO Author(Author_ID,author_fullname) VALUES (72,'Percival Arnke');
INSERT INTO Author(Author_ID,author_fullname) VALUES (73,'Elayne Yerrill');
INSERT INTO Author(Author_ID,author_fullname) VALUES (74,'Myer Aishford');
INSERT INTO Author(Author_ID,author_fullname) VALUES (75,'Ashton Ancell');
INSERT INTO Author(Author_ID,author_fullname) VALUES (76,'Arley Sawers');
INSERT INTO Author(Author_ID,author_fullname) VALUES (77,'Barton Sizzey');
INSERT INTO Author(Author_ID,author_fullname) VALUES (78,'Gerrie Driffe');
INSERT INTO Author(Author_ID,author_fullname) VALUES (79,'Francesca Linning');
INSERT INTO Author(Author_ID,author_fullname) VALUES (80,'Lay Van der Brug');


INSERT INTO book_author(Book_ID,Author_ID) VALUES (17,63);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (43,79);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (9,66);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (41,15);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (66,33);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (66,27);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (6,38);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (26,7);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (98,20);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (81,45);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (61,1);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (18,7);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (84,64);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (76,33);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (33,58);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (43,6);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (31,51);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (98,22);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (75,39);

INSERT INTO book_author(Book_ID,Author_ID) VALUES (13,36);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (89,50);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (48,18);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (33,49);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (56,78);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (58,33);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (52,27);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (12,13);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (23,30);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (17,78);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (31,12);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (73,73);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (5,51);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (15,74);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (82,55);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (11,36);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (43,55);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (60,8);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (95,36);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (26,60);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (11,44);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (76,34);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (92,46);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (95,40);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (36,37);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (98,59);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (25,1);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (55,73);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (39,31);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (92,41);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (86,17);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (72,65);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (89,8);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (60,15);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (76,67);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (55,38);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (56,54);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (67,75);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (52,72);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (69,68);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (54,76);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (75,65);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (98,21);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (42,3);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (58,73);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (4,25);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (55,68);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (63,30);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (76,15);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (57,69);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (13,29);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (79,65);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (67,34);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (99,57);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (87,68);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (57,40);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (19,71);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (10,70);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (37,46);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (91,36);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (2,74);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (47,58);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (32,56);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (22,75);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (3,78);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (1,15);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (58,53);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (24,26);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (17,18);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (37,7);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (61,18);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (9,19);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (54,79);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (2,3);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (92,55);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (69,14);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (46,43);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (74,69);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (98,35);
INSERT INTO book_author(Book_ID,Author_ID) VALUES (51,19);

INSERT INTO Category (Category_ID, category) VALUES ('1', 'Fiction');
INSERT INTO Category (Category_ID, category) VALUES ('2', 'Mystery');
INSERT INTO Category (Category_ID, category) VALUES ('3', 'Romance');
INSERT INTO Category (Category_ID, category) VALUES ('4', 'Science Fiction');
INSERT INTO Category (Category_ID, category) VALUES ('5', 'Fantasy');
INSERT INTO Category (Category_ID, category) VALUES ('6', 'Thriller');
INSERT INTO Category (Category_ID, category) VALUES ('7', 'Horror');
INSERT INTO Category (Category_ID, category) VALUES ('8', 'Historical Fiction');
INSERT INTO Category (Category_ID, category) VALUES ('9', 'Biography');
INSERT INTO Category (Category_ID, category) VALUES ('10', 'Self-Help');
INSERT INTO Category (Category_ID, category) VALUES ('11', 'Poetry');
INSERT INTO Category (Category_ID, category) VALUES ('12', 'Memoir');
INSERT INTO Category (Category_ID, category) VALUES ('13', 'Travel');
INSERT INTO Category (Category_ID, category) VALUES ('14', 'Business');
INSERT INTO Category (Category_ID, category) VALUES ('15', 'Science');
INSERT INTO Category (Category_ID, category) VALUES ('16', 'Philosophy');
INSERT INTO Category (Category_ID, category) VALUES ('17', 'Psychology');
INSERT INTO Category (Category_ID, category) VALUES ('18', 'Art');
INSERT INTO Category (Category_ID, category) VALUES ('19', 'Cooking');
INSERT INTO Category (Category_ID, category) VALUES ('20', 'History');
INSERT INTO Category (Category_ID, category) VALUES ('21', 'Religion');
INSERT INTO Category (Category_ID, category) VALUES ('22', 'Health and Fitness');
INSERT INTO Category (Category_ID, category) VALUES ('23', 'Education');
INSERT INTO Category (Category_ID, category) VALUES ('24', 'Sports');
INSERT INTO Category (Category_ID, category) VALUES ('25', 'Technology');
INSERT INTO Category (Category_ID, category) VALUES ('26', 'Parenting');
INSERT INTO Category (Category_ID, category) VALUES ('27', 'Music');
INSERT INTO Category (Category_ID, category) VALUES ('28', 'Nature and Environment');
INSERT INTO Category (Category_ID, category) VALUES ('29', 'Politics');
INSERT INTO Category (Category_ID, category) VALUES ('30', 'Humor');


INSERT INTO book_category(Book_ID,Category_ID) VALUES (85,6);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (6,2);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (61,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (92,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (82,19);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (82,16);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (25,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (24,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (7,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (68,10);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (47,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (45,25);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (46,30);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (78,8);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (26,17);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (60,3);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (24,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (2,12);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (68,9);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (95,21);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (74,9);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (37,24);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (46,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (19,28);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (83,17);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (6,16);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (59,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (13,3);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (32,24);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (45,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (6,12);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (80,22);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (94,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (98,15);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (86,28);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (57,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (29,9);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (6,27);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (58,2);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (97,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (70,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (4,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (96,29);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (72,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (34,1);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (75,22);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (39,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (11,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (88,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (43,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (53,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (37,22);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (20,30);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (60,29);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (58,9);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (18,4);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (49,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (59,10);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (81,26);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (3,6);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (17,16);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (50,28);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (34,11);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (47,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (96,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (4,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (60,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (85,14);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (73,30);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (58,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (83,13);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (60,15);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (23,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (70,21);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (80,26);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (24,15);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (38,21);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (41,1);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (91,29);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (65,18);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (24,10);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (14,24);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (90,5);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (64,14);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (13,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (15,25);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (9,30);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (56,6);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (62,8);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (40,18);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (25,14);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (35,3);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (77,7);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (96,18);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (11,6);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (90,1);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (72,23);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (23,24);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (16,10);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (62,2);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (23,14);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (16,3);
INSERT INTO book_category(Book_ID,Category_ID) VALUES (62,7);










INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (59,1,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (38,2,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (19,3,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (13,5,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (94,4,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (46,4,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (41,5,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (87,2,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (76,1,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (47,3,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (77,4,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (93,1,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (100,3,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (99,2,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (79,5,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (46,3,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (12,2,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (61,5,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (65,1,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (97,1,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (11,4,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (14,2,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (84,5,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (25,5,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (83,2,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (69,3,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (64,1,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (43,1,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (91,2,9);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (3,5,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (12,4,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (84,3,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (40,1,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (67,5,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (30,3,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (65,2,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (81,4,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (25,4,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (35,2,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (60,5,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (7,3,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (51,1,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (59,2,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (28,5,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (99,4,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (89,3,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (85,1,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (18,2,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (74,5,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (67,1,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (53,4,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (44,3,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (96,1,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (1,4,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (85,3,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (51,5,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (61,2,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (72,2,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (32,4,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (12,3,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (30,5,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (75,5,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (13,3,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (40,4,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (73,2,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (87,1,10);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (80,3,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (95,5,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (98,4,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (53,2,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (25,2,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (72,1,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (57,3,8);

INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (90,5,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (49,3,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (42,5,8);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (20,1,6);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (67,2,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (67,4,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (77,1,6);


INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (79,2,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (57,1,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (35,5,5);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (37,4,1);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (1,2,4);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (62,3,3);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (62,2,7);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (66,5,2);
INSERT INTO school_book(Book_ID,School_ID,Available_Copies) VALUES (88,3,1);


INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('1', '29', '1', '1', '2023-10-05', '2023-04-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('2', '41', '2', '2', '2023-05-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('3', '22', '3', '3', '2023-08-05', '2023-10-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('4', '40', '4', '4', '2023-05-29', '2023-12-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('5', '45', '5', '5', '2023-04-05', '2023-05-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('6', '79', '1', '6', '2023-05-14', '2023-06-16');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('7', '29', '2', '7', '2023-05-24', '2023-06-16');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('8', '83', '3', '8', '2023-05-30', '2023-06-17');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('9', '32', '4', '9', '2023-04-29', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('10', '83', '5', '10', '2023-04-30', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('11', '85', '1', '11', '2023-04-30', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('12', '49', '2', '12', '2023-09-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('13', '91', '3', '13', '2023-05-26', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('14', '47', '4', '14', '2023-05-14', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('15', '75', '5', '15', '2023-09-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('16', '86', '1', '16', '2023-05-15', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('17', '21', '2', '17', '2023-04-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('18', '69', '3', '18', '2023-05-14', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('19', '77', '4', '19', '2023-05-31', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('20', '89', '5', '20', '2023-05-17', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('21', '95', '1', '21', '2023-01-06', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('22', '98', '2', '22', '2023-03-06', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('23', '22', '3', '23', '2023-05-15', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('24', '52', '4', '24', '2023-07-05', '2023-12-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('25', '36', '5', '25', '2023-02-05', '2023-06-13');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('26', '26', '1', '26', '2023-05-13', '2023-06-15');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('27', '23', '2', '27', '2023-04-06', '2023-08-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('28', '98', '3', '28', '2023-09-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('29', '79', '4', '29', '2023-03-05', '2023-04-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('30', '1', '5', '30', '2023-07-05', '2023-06-13');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('31', '52', '1', '31', '2023-04-28', '2023-12-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('32', '18', '2', '32', '2023-05-31', '2023-06-15');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('33', '41', '3', '33', '2023-09-05', '2023-06-18');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('34', '42', '4', '34', '2023-07-05', '2023-06-13');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('35', '30', '5', '35', '2023-05-31', '2023-06-16');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('36', '68', '1', '36', '2023-01-06', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('37', '59', '2', '37', '2023-05-27', '2023-06-13');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('38', '87', '3', '38', '2023-05-05', '2023-06-15');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('39', '56', '4', '39', '2023-05-20', '2023-06-18');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('40', '71', '5', '40', '2023-06-05', '2023-06-16');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('41', '82', '1', '2', '2023-09-05', '2023-12-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('42', '69', '2', '24', '2023-10-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('43', '1', '3', '39', '2023-04-29', '2023-05-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('44', '61', '4', '38', '2023-05-21', '2023-05-24');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('45', '25', '5', '1', '2023-09-05', NULL);
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('46', '21', '1', '20', '2023-05-16', '2023-12-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('47', '35', '2', '15', '2023-05-22', '2023-05-27');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('48', '84', '3', '21', '2023-02-06', '2023-07-06');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('49', '7', '4', '12', '2023-05-06', '2023-06-19');
INSERT INTO Loan (loan_id, Book_ID, Manager_ID, studprof_id, loan_date, date_returned) VALUES ('50', '79', '5', '26', '2023-04-29', '2023-06-19');






INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('1', '51', '5', '37', '2023-06-08');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('2', '38', '2', '16', '2023-06-08');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('3', '90', '5', '39', '2023-06-07');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('4', '43', '4', '22', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('5', '19', '4', '23', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('6', '88', '2', '14', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('7', '46', '4', '1', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('8', '84', '1', '16', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('9', '41', '3', '20', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('10', '42', '1', '2', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('11', '28', '3', '9', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('12', '19', '2', '39', '2023-06-08');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('13', '22', '4', '1', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('14', '43', '3', '9', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('15', '2', '3', '9', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('16', '45', '2', '22', '2023-06-10');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('17', '63', '2', '6', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('18', '94', '3', '9', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('19', '77', '1', '17', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('20', '7', '3', '26', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('21', '21', '3', '18', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('22', '37', '1', '34', '2023-06-07');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('23', '9', '1', '2', '2023-06-10');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('24', '10', '3', '14', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('25', '6', '1', '7', '2023-06-12');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('26', '24', '5', '38', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('27', '80', '3', '24', '2023-06-05');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('28', '25', '5', '15', '2023-06-04');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('29', '36', '3', '12', '2023-06-10');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('30', '48', '5', '33', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('31', '65', '1', '14', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('32', '22', '2', '23', '2023-06-11');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('33', '49', '5', '31', '2023-06-04');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('34', '90', '4', '5', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('35', '89', '4', '14', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('36', '3', '1', '4', '2023-06-08');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('37', '2', '5', '31', '2023-06-06');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('38', '73', '3', '39', '2023-06-13');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('39', '86', '3', '24', '2023-06-09');
INSERT INTO Reservation (reservation_id, Book_ID, Manager_ID, studprof_id, reservation_date) VALUES ('40', '7', '2', '33', '2023-06-05');




INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('1', '2022-08-21', '2024-10-10', '1', '1');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('2', '2020-06-06', '2024-08-06', '2', '2');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('3', '2023-05-31', '2023-05-31', '3', '3');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('4', '2020-12-12', '2025-10-01', '4', '4');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('5', '2022-02-26', '2024-08-05', '5', '5');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('6', '2019-06-23', '2024-03-22', '1', '6');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('7', '2023-08-04', '2024-06-08', '2', '7');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('8', '2022-05-11', '2025-08-02', '3', '8');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('9', '2021-02-27', '2024-09-10', '4', '9');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('10', '2021-07-03', '2023-08-27', '5', '10');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('11', '2020-02-26', '2023-09-10', '1', '11');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('12', '2022-03-06', '2025-01-27', '2', '12');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('13', '2023-03-22', '2024-04-05', '3', '13');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('14', '2021-08-02', '2023-08-08', '4', '14');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('15', '2021-10-30', '2024-12-06', '5', '15');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('16', '2021-09-24', '2024-06-07', '1', '16');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('17', '2022-05-01', '2024-10-25', '2', '17');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('18', '2022-11-16', '2024-06-10', '3', '18');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('19', '2019-02-11', '2024-12-06', '4', '19');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('20', '2019-08-23', '2024-11-13', '5', '20');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('21', '2021-08-09', '2024-06-30', '1', '21');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('22', '2019-11-15', '2024-06-12', '2', '22');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('23', '2021-04-18', '2024-01-18', '3', '23');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('24', '2022-05-12', '2024-07-21', '4', '24');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('25', '2023-07-05', '2025-12-03', '5', '25');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('26', '2019-11-07', '2024-04-24', '1', '26');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('27', '2021-04-06', '2024-08-26', '2', '27');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('28', '2019-12-09', '2023-09-30', '3', '28');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('29', '2022-02-27', '2023-12-27', '4', '29');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('30', '2022-01-27', '2023-12-11', '5', '30');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('31', '2020-02-24', '2024-07-01', '1', '31');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('32', '2020-09-25', '2023-07-13', '2', '32');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('33', '2020-06-22', '2024-08-17', '3', '33');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('34', '2020-08-05', '2023-11-07', '4', '34');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('35', '2022-09-24', '2024-01-13', '5', '35');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('36', '2022-12-04', '2025-01-02', '1', '36');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('37', '2023-02-06', '2025-03-14', '2', '37');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('38', '2019-10-06', '2025-10-03', '3', '38');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('39', '2022-04-22', '2024-07-25', '4', '39');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('40', '2020-10-19', '2023-06-12', '5', '40');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('41', '2020-08-30', '2025-05-24', '1', '2');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('42', '2022-11-05', '2025-02-05', '2', '24');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('43', '2020-01-07', '2023-07-24', '3', '39');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('44', '2020-04-08', '2024-08-05', '4', '38');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('45', '2022-03-02', '2024-03-07', '5', '1');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('46', '2022-04-18', '2023-10-27', '1', '20');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('47', '2019-11-19', '2024-11-16', '2', '15');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('48', '2019-12-09', '2024-05-19', '3', '21');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('49', '2021-02-15', '2023-12-11', '4', '12');
INSERT INTO Borrower_Card (Card_ID, Date_issued, Date_expired, Manager_ID, studprof_id) VALUES ('50', '2020-01-12', '2025-04-28', '5', '26');



INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('1', '67', '12', '2', '4', '0', 'I found the book to be thought-provoking and insightful.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('2', '76', '1', '5', '2', '0', 'The themes explored in the book were relevant and important.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('3', '7', '28', '3', '4', '1', 'The ending was satisfying and tied up all loose ends.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('4', '70', '12', '2', '2', '0', 'The ending was satisfying and tied up all loose ends.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('5', '15', '47', '4', '2', '1', 'The ending was not satisfying but still enjoyable.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('6', '39', '45', '2', '1', '0', 'The ending was not satisfying but still good.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('7', '74', '1', '5', '5', '1', 'The writing style was beautiful and poetic.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('8', '100', '36', '2', '2', '0', 'The plot was engaging and kept me hooked until the end.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('9', '43', '4', '1', '4', '1', 'I appreciated the author\'s use of symbolism throughout the story.');
INSERT INTO Review (review_id, Book_id, User_ID, Manager_ID, likert_scale, approved, review) VALUES ('10', '92', '36', '1', '3', '0', 'The characters were well-developed and relatable.');



